import { redirect } from 'next/navigation'
import { GitCompare, MessageSquareText } from 'lucide-react'
import { WorkspaceNav } from '@/components/workspace-nav'
import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { addReviewCommentAction } from '@/app/actions/advanced-experience'

export const dynamic='force-dynamic'
type Item={id:string;type:'control'|'policy'|'snapshot';title:string;current:string;source:string;status:string}
type Comment={id:string;entity_type:string;entity_id:string;comment_type:string;body:string;created_at:string}

export default async function ReviewComparePage(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/sign-in?next=/review-center/compare')
 const admin=createAdminClient();const {data:membership}=await admin.from('organization_members').select('organization_id').eq('user_id',user.id).limit(1).maybeSingle();if(!membership?.organization_id)redirect('/onboarding');const org=membership.organization_id
 const [controls,policies,snapshots,comments]=await Promise.all([
  admin.from('controls').select('id,name,description,control_objective,status').eq('organization_id',org).in('lifecycle_status',['draft','active']).limit(20),
  admin.from('organization_policy_instances').select('id,title,status,content,policy_catalog_version_id').eq('organization_id',org).in('status',['draft','in_review','approved']).limit(20),
  admin.from('executive_intelligence_snapshots').select('id,status,executive_summary,source_metrics,period_start,period_end').eq('organization_id',org).order('generated_at',{ascending:false}).limit(10),
  admin.from('review_comments').select('id,entity_type,entity_id,comment_type,body,created_at').eq('organization_id',org).order('created_at',{ascending:false}).limit(100),
 ])
 const items:Item[]=[...(controls.data||[]).map(x=>({id:x.id,type:'control' as const,title:x.name,current:x.description||x.control_objective||'Sin descripción',source:x.control_objective||'Sin objetivo canónico',status:x.status})),...(policies.data||[]).map(x=>({id:x.id,type:'policy' as const,title:x.title,current:JSON.stringify(x.content,null,2),source:`Plantilla ${x.policy_catalog_version_id}`,status:x.status})),...(snapshots.data||[]).map(x=>({id:x.id,type:'snapshot' as const,title:`Snapshot ${x.period_start} - ${x.period_end}`,current:JSON.stringify(x.executive_summary,null,2),source:JSON.stringify(x.source_metrics,null,2),status:x.status}))]
 const notes=(comments.data||[]) as Comment[]
 return <><WorkspaceNav/><main className="container mx-auto space-y-8 px-4 py-8 sm:px-6"><header className="rounded-3xl border bg-card p-6 sm:p-8"><div className="flex items-center gap-2 text-primary"><GitCompare className="h-5 w-5"/><p className="text-sm font-bold">Review Center</p></div><h1 className="mt-3 text-3xl font-extrabold">Comparación y comentarios</h1><p className="mt-3 text-muted-foreground">Compara el borrador con su fuente y deja solicitudes de cambio antes de aprobar.</p></header><section className="space-y-6">{items.map(item=>{const itemNotes=notes.filter(note=>note.entity_type===item.type&&note.entity_id===item.id);return <article key={`${item.type}-${item.id}`} className="rounded-2xl border bg-card"><div className="flex flex-wrap items-center gap-3 border-b p-5"><span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-bold text-primary">{item.type}</span><h2 className="font-bold">{item.title}</h2><span className="ml-auto text-xs text-muted-foreground">{item.status}</span></div><div className="grid gap-px bg-border lg:grid-cols-2"><DiffPanel label="Fuente / antes" text={item.source} tone="before"/><DiffPanel label="Borrador / después" text={item.current} tone="after"/></div><div className="grid gap-5 border-t p-5 lg:grid-cols-2"><div><h3 className="flex items-center gap-2 font-bold"><MessageSquareText className="h-4 w-4"/>Comentarios</h3><div className="mt-3 space-y-2">{itemNotes.map(note=><div key={note.id} className="rounded-xl bg-muted/60 p-3 text-sm"><strong>{note.comment_type}</strong><p className="mt-1 whitespace-pre-wrap text-muted-foreground">{note.body}</p></div>)}{!itemNotes.length&&<p className="text-sm text-muted-foreground">Sin comentarios.</p>}</div></div><form action={addReviewCommentAction} className="space-y-3"><input type="hidden" name="entityType" value={item.type}/><input type="hidden" name="entityId" value={item.id}/><select name="commentType" className="w-full rounded-lg border bg-background px-3 py-2"><option value="comment">Comentario</option><option value="change_request">Solicitud de cambio</option><option value="decision_note">Nota de decisión</option></select><textarea name="body" required maxLength={4000} className="min-h-24 w-full rounded-lg border bg-background px-3 py-2" placeholder="Escribe una observación trazable..."/><button className="rounded-xl bg-primary px-4 py-2 font-bold text-primary-foreground">Guardar comentario</button></form></div></article>})}{!items.length&&<p className="rounded-2xl border bg-card p-8 text-center text-muted-foreground">No hay elementos comparables.</p>}</section></main></>
}
function DiffPanel({label,text,tone}:{label:string;text:string;tone:'before'|'after'}){return <section className="bg-card p-5"><p className={`text-xs font-bold ${tone==='before'?'text-red-600':'text-emerald-600'}`}>{tone==='before'?'-':'+'} {label}</p><pre className="mt-3 max-h-72 overflow-auto whitespace-pre-wrap break-words rounded-xl bg-muted/40 p-4 text-xs leading-6">{text}</pre></section>}
