import Link from 'next/link'
import { redirect } from 'next/navigation'
import { ArrowRight, Files } from 'lucide-react'
import { WorkspaceNav } from '@/components/workspace-nav'
import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'

export const dynamic='force-dynamic'
type Snapshot={id:string;status:string;period_start:string;period_end:string;overall_risk_score:number|null;critical_risks:number;open_impacts:number;overdue_actions:number;expiring_evidence:number;control_coverage_pct:number|null;evidence_confidence_pct:number|null;generated_at:string}
const metrics:[keyof Snapshot,string][]=[['overall_risk_score','Riesgo general'],['critical_risks','Riesgos críticos'],['open_impacts','Impactos abiertos'],['overdue_actions','Acciones vencidas'],['expiring_evidence','Evidencias por vencer'],['control_coverage_pct','Cobertura de controles'],['evidence_confidence_pct','Confianza de evidencia']]

export default async function ExecutiveComparePage(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/sign-in?next=/executive/compare')
 const admin=createAdminClient();const {data:membership}=await admin.from('organization_members').select('organization_id').eq('user_id',user.id).limit(1).maybeSingle();if(!membership?.organization_id)redirect('/onboarding')
 const {data}=await admin.from('executive_intelligence_snapshots').select('id,status,period_start,period_end,overall_risk_score,critical_risks,open_impacts,overdue_actions,expiring_evidence,control_coverage_pct,evidence_confidence_pct,generated_at').eq('organization_id',membership.organization_id).order('generated_at',{ascending:false}).limit(12)
 const snapshots=(data||[]) as Snapshot[];const current=snapshots[0];const previous=snapshots[1]
 return <><WorkspaceNav/><main className="container mx-auto space-y-8 px-4 py-8 sm:px-6"><header className="rounded-3xl border bg-card p-6 sm:p-8"><div className="flex items-center gap-2 text-primary"><Files className="h-5 w-5"/><p className="text-sm font-bold">Executive Intelligence</p></div><h1 className="mt-3 text-3xl font-extrabold">Comparación histórica</h1><p className="mt-3 text-muted-foreground">Compara los dos snapshots más recientes y abre cualquier período como reporte imprimible.</p></header>{current&&previous?<section className="rounded-2xl border bg-card"><div className="grid grid-cols-[1fr_120px_120px_90px] gap-3 border-b p-4 text-xs font-bold text-muted-foreground"><span>Métrica</span><span>Anterior</span><span>Actual</span><span>Cambio</span></div>{metrics.map(([key,label])=>{const before=Number(previous[key]??0);const after=Number(current[key]??0);const delta=after-before;return <div key={String(key)} className="grid grid-cols-[1fr_120px_120px_90px] gap-3 border-b p-4 text-sm last:border-0"><strong>{label}</strong><span>{format(key,before)}</span><span>{format(key,after)}</span><span className={delta>0?'text-amber-600':delta<0?'text-emerald-600':'text-muted-foreground'}>{delta>0?'+':''}{format(key,delta)}</span></div>})}</section>:<p className="rounded-2xl border bg-card p-8 text-center text-muted-foreground">Se requieren al menos dos snapshots para comparar.</p>}<section className="space-y-3">{snapshots.map(snapshot=><article key={snapshot.id} className="flex flex-col gap-4 rounded-2xl border bg-card p-5 sm:flex-row sm:items-center"><div><p className="text-xs font-bold text-primary">{snapshot.period_start} - {snapshot.period_end}</p><h2 className="mt-1 font-bold">{snapshot.status}</h2><p className="mt-1 text-xs text-muted-foreground">Generado {new Date(snapshot.generated_at).toLocaleString('es-CL')}</p></div><Link href={`/executive/report/${snapshot.id}`} className="ml-auto inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-sm font-bold">Abrir reporte <ArrowRight className="h-4 w-4"/></Link></article>)}</section></main></>
}
function format(key:keyof Snapshot,value:number){return ['control_coverage_pct','evidence_confidence_pct'].includes(String(key))?`${Math.round(value)}%`:Number.isInteger(value)?String(value):value.toFixed(1)}
